# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public/uploads'

    resolvers:
        icons:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: uploads/icons
        profile_pictures:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: uploads/profile_pictures
